  client_config_backend: file
  client_config:
    client_id: #your client id should be here
    client_secret: #your client secret should be here

  save_credentials: True
  save_credentials_backend: file
  save_credentials_file: credentials.json

  get_refresh_token: True

  oauth_scope: 
      - https://www.googleapis.com/auth/drive
      - https://www.googleapis.com/auth/drive.install